from models import Mention, Platform, Sentiment, TriageLabel

MENTIONS = [
    Mention(
        id="1",
        platform=Platform.twitter,
        author="@frustrated_renter_bandra",
        author_followers=1240,
        content="Housing.com showed me 47 listings in Andheri West. Called 30+ agents. Every. Single. One. was fake or already rented. Three weekends WASTED. This is straight up fraud. @HousingDotCom #FakeListings #HousingScam",
        sentiment=Sentiment.negative,
        triage=TriageLabel.urgent,
        timestamp="2026-05-04T09:23:00",
        reach=8400,
        likes=312,
        shares=289,
        is_crisis=True,
    ),
    Mention(
        id="2",
        platform=Platform.reddit,
        author="u/bangalore_house_hunt",
        author_followers=0,
        content="PSA for Bangalore folks: Housing.com listings in Koramangala and HSR are 60-70% fake. I wasted 3 weekends visiting properties that were 'already rented' the moment I showed up. Agents just use it to generate leads. Switching to NoBroker.",
        sentiment=Sentiment.negative,
        triage=TriageLabel.urgent,
        timestamp="2026-05-04T08:10:00",
        reach=2100,
        likes=847,
        shares=156,
        is_crisis=True,
    ),
    Mention(
        id="3",
        platform=Platform.twitter,
        author="@rohit_techbro",
        author_followers=3800,
        content="My Housing.com account was hacked and now I'm getting calls from random brokers across Mumbai. They CLEARLY sold my personal data. @HousingDotCom you have 24 hours to respond or I'm filing a complaint with CERT-In. #DataBreach #HousingDotCom",
        sentiment=Sentiment.negative,
        triage=TriageLabel.urgent,
        timestamp="2026-05-04T07:45:00",
        reach=15200,
        likes=1240,
        shares=634,
        is_crisis=True,
    ),
    Mention(
        id="4",
        platform=Platform.google,
        author="Priya Sharma",
        author_followers=0,
        content="1 star. Paid ₹4,999 for premium subscription. Listings are outdated by 3-4 months. Called Housing.com support, they put me on hold for 45 minutes and disconnected. Absolute scam. Going to consumer court.",
        sentiment=Sentiment.negative,
        triage=TriageLabel.urgent,
        timestamp="2026-05-03T18:30:00",
        reach=400,
        likes=0,
        shares=0,
    ),
    Mention(
        id="5",
        platform=Platform.twitter,
        author="@delhi_home_seeker",
        author_followers=890,
        content="The Housing.com app crashed FOUR TIMES during my virtual tour of a 2BHK in Dwarka. Lost the property to someone else. Absolute garbage app. @HousingDotCom sort your servers out.",
        sentiment=Sentiment.negative,
        triage=TriageLabel.urgent,
        timestamp="2026-05-03T16:15:00",
        reach=3200,
        likes=198,
        shares=87,
    ),
    Mention(
        id="6",
        platform=Platform.twitter,
        author="@TechWithRahul",
        author_followers=245000,
        content="I compared Housing.com, MagicBricks, and 99acres for 30 days while apartment hunting in Pune. Full honest review thread. Spoiler: one of them has a massive fake listing problem 🧵 (1/12)",
        sentiment=Sentiment.neutral,
        triage=TriageLabel.influencer,
        timestamp="2026-05-03T14:00:00",
        reach=89000,
        likes=4200,
        shares=2100,
    ),
    Mention(
        id="7",
        platform=Platform.twitter,
        author="@PropertyAdvice_India",
        author_followers=89000,
        content="Housing.com's new AI-powered search filters are genuinely impressive — best in class UX for real estate discovery. But their agent response rate is still averaging 48+ hours. The tech is ahead of the ops. @HousingDotCom",
        sentiment=Sentiment.neutral,
        triage=TriageLabel.influencer,
        timestamp="2026-05-02T11:30:00",
        reach=34000,
        likes=1890,
        shares=423,
    ),
    Mention(
        id="8",
        platform=Platform.twitter,
        author="@MumbaiRealEstateInsider",
        author_followers=156000,
        content="Breaking: Housing.com is rolling out 'Verified Listing' badges in Mumbai and Bangalore by June. This could be a game-changer for their fake listing problem if executed well. Watching closely. @HousingDotCom",
        sentiment=Sentiment.positive,
        triage=TriageLabel.influencer,
        timestamp="2026-05-02T09:00:00",
        reach=62000,
        likes=3100,
        shares=980,
    ),
    Mention(
        id="9",
        platform=Platform.reddit,
        author="u/pune_apartment_seeker",
        author_followers=0,
        content="Genuinely impressed by Housing.com's map-based search. Being able to draw a custom polygon around my preferred area and filter by commute time to office is something neither MagicBricks nor 99acres has. Good stuff.",
        sentiment=Sentiment.positive,
        triage=TriageLabel.neutral,
        timestamp="2026-05-02T20:45:00",
        reach=890,
        likes=234,
        shares=0,
    ),
    Mention(
        id="10",
        platform=Platform.playstore,
        author="Arjun Mehta",
        author_followers=0,
        content="5 stars. Finally found my 3BHK in Powai through Housing.com after 2 months of searching. The photo quality and floor plans are so much better than other apps. Agent was responsive too. Highly recommend!",
        sentiment=Sentiment.positive,
        triage=TriageLabel.neutral,
        timestamp="2026-05-01T15:20:00",
        reach=200,
        likes=45,
        shares=0,
    ),
    Mention(
        id="11",
        platform=Platform.twitter,
        author="@chennai_it_guy",
        author_followers=2300,
        content="Housing.com showing me ₹45k/month apartments in Chennai's OMR when I set filter to ₹20k max. Either their algorithm is broken or they're just showing fake listings to inflate numbers. @HousingDotCom fix this!",
        sentiment=Sentiment.negative,
        triage=TriageLabel.neutral,
        timestamp="2026-05-01T12:00:00",
        reach=1800,
        likes=89,
        shares=34,
    ),
    Mention(
        id="12",
        platform=Platform.google,
        author="Sneha Kapoor",
        author_followers=0,
        content="4 stars. Good app overall. Lots of listings in Gurgaon, found a great place in Sector 49. Only complaint is too many broker calls after posting my requirement. Wish there was a do-not-disturb option.",
        sentiment=Sentiment.positive,
        triage=TriageLabel.neutral,
        timestamp="2026-04-30T09:15:00",
        reach=150,
        likes=12,
        shares=0,
    ),
    Mention(
        id="13",
        platform=Platform.twitter,
        author="@hyderabad_techie_ravi",
        author_followers=670,
        content="Housing.com customer support is non-existent. Raised a ticket about duplicate listings 2 weeks ago. Zero response. @HousingDotCom this is basic stuff.",
        sentiment=Sentiment.negative,
        triage=TriageLabel.neutral,
        timestamp="2026-04-29T17:30:00",
        reach=890,
        likes=45,
        shares=12,
    ),
    Mention(
        id="14",
        platform=Platform.reddit,
        author="u/noida_first_time_buyer",
        author_followers=0,
        content="For buying (not renting) Housing.com is actually quite good. Good loan EMI calculator integration, RERA compliance info on listings, and builder reputation scores. Much better than 99acres for purchase decisions.",
        sentiment=Sentiment.positive,
        triage=TriageLabel.neutral,
        timestamp="2026-04-28T14:00:00",
        reach=560,
        likes=178,
        shares=23,
    ),
    Mention(
        id="15",
        platform=Platform.playstore,
        author="Rahul Desai",
        author_followers=0,
        content="2 stars. App is good but listings are outdated. Same properties appearing as available for months. Please update your database more frequently. Also the search is slow on 4G.",
        sentiment=Sentiment.negative,
        triage=TriageLabel.neutral,
        timestamp="2026-04-27T10:45:00",
        reach=100,
        likes=23,
        shares=0,
    ),
]

SOV_TREND = [
    # Dec 2025 → May 2026 — design-shaped curves; Feb anchors match Figma tooltip (99acres 90, nobroker 52, housing 50, magicbricks 34).
    {"month": "Dec", "housing": 42, "magicbricks": 31, "99acres": 58, "nobroker": 24},
    {"month": "Jan", "housing": 46, "magicbricks": 33, "99acres": 74, "nobroker": 22},
    {"month": "Feb", "housing": 50, "magicbricks": 34, "99acres": 90, "nobroker": 52},
    {"month": "Mar", "housing": 44, "magicbricks": 49, "99acres": 68, "nobroker": 54},
    {"month": "Apr", "housing": 52, "magicbricks": 43, "99acres": 84, "nobroker": 57},
    {"month": "May", "housing": 48, "magicbricks": 46, "99acres": 96, "nobroker": 60},
]

GEO_DATA = {
    "query": "best real estate portal in India to find apartments for rent",
    "results": [
        {
            "llm": "ChatGPT",
            "housing_mentions": 3,
            "competitor_mentions": {"MagicBricks": 12, "99acres": 8, "NoBroker": 6},
            "sentiment": "neutral",
            "cited_urls": [
                "magicbricks.com/advice/top-portals",
                "99acres.com/blog/best-sites",
                "housing.com/news/about-us",
            ],
            "ai_share_of_voice": 12.5,
        },
        {
            "llm": "Gemini",
            "housing_mentions": 4,
            "competitor_mentions": {"NoBroker": 10, "MagicBricks": 7, "99acres": 5},
            "sentiment": "neutral",
            "cited_urls": [
                "nobroker.in/blog/best-apps",
                "magicbricks.com",
                "housing.com",
            ],
            "ai_share_of_voice": 15.4,
        },
        {
            "llm": "Perplexity",
            "housing_mentions": 5,
            "competitor_mentions": {"99acres": 9, "MagicBricks": 6, "NoBroker": 4},
            "sentiment": "positive",
            "cited_urls": [
                "housing.com/research/india-rental-report",
                "99acres.com",
                "magicbricks.com",
            ],
            "ai_share_of_voice": 20.8,
        },
    ],
    "semantic_gaps": [
        "Housing.com is not mentioned when users ask about 'verified listings India'",
        "No citations for queries like 'best app for PG in Bangalore' or 'furnished flat Mumbai'",
        "ChatGPT does not associate Housing.com with 'RERA-compliant properties'",
        "Missing from LLM responses about 'NRI property investment India'",
    ],
    "recommendations": [
        "Publish a detailed 'How Housing.com verifies listings' blog post to get cited by LLMs",
        "Add FAQ schema markup to your verified listings pages",
        "Create a landing page targeting 'furnished apartments [city]' — competitors dominate this query in LLMs",
        "Get cited in at least 2 more authoritative real estate publications to improve LLM training signal",
    ],
}

TRUST_SCORE_TREND = [
    {"date": "Apr 6", "score": 72},
    {"date": "Apr 13", "score": 69},
    {"date": "Apr 20", "score": 65},
    {"date": "Apr 27", "score": 61},
    {"date": "May 4", "score": 58},
]

# --- Dashboard time ranges (query ?range=7d|1m|3m|6m|1y) ---

VALID_TIME_RANGES = frozenset({"7d", "1m", "3m", "6m", "1y"})
DEFAULT_TIME_RANGE = "6m"


def normalize_time_range(value: str | None) -> str:
    if value and value.strip().lower() in VALID_TIME_RANGES:
        return value.strip().lower()
    return DEFAULT_TIME_RANGE


SOV_TREND_BY_RANGE = {
    "7d": [
        {"month": "Mon", "housing": 44, "magicbricks": 29, "99acres": 61, "nobroker": 27},
        {"month": "Tue", "housing": 46, "magicbricks": 30, "99acres": 63, "nobroker": 28},
        {"month": "Wed", "housing": 45, "magicbricks": 31, "99acres": 62, "nobroker": 29},
        {"month": "Thu", "housing": 47, "magicbricks": 32, "99acres": 64, "nobroker": 28},
        {"month": "Fri", "housing": 48, "magicbricks": 33, "99acres": 65, "nobroker": 30},
        {"month": "Sat", "housing": 47, "magicbricks": 32, "99acres": 64, "nobroker": 31},
        {"month": "Sun", "housing": 46, "magicbricks": 31, "99acres": 62, "nobroker": 30},
    ],
    "1m": [
        {"month": "W1", "housing": 43, "magicbricks": 30, "99acres": 59, "nobroker": 26},
        {"month": "W2", "housing": 45, "magicbricks": 31, "99acres": 67, "nobroker": 28},
        {"month": "W3", "housing": 47, "magicbricks": 33, "99acres": 72, "nobroker": 32},
        {"month": "W4", "housing": 46, "magicbricks": 34, "99acres": 78, "nobroker": 48},
    ],
    "3m": [
        {"month": "Mar", "housing": 44, "magicbricks": 49, "99acres": 68, "nobroker": 54},
        {"month": "Apr", "housing": 52, "magicbricks": 43, "99acres": 84, "nobroker": 57},
        {"month": "May", "housing": 48, "magicbricks": 46, "99acres": 96, "nobroker": 60},
    ],
    "6m": SOV_TREND,
    "1y": [
        {"month": "Jun", "housing": 38, "magicbricks": 28, "99acres": 52, "nobroker": 22},
        {"month": "Jul", "housing": 40, "magicbricks": 29, "99acres": 55, "nobroker": 23},
        {"month": "Aug", "housing": 41, "magicbricks": 30, "99acres": 58, "nobroker": 23},
        {"month": "Sep", "housing": 42, "magicbricks": 30, "99acres": 58, "nobroker": 24},
        {"month": "Oct", "housing": 41, "magicbricks": 31, "99acres": 57, "nobroker": 24},
        {"month": "Nov", "housing": 42, "magicbricks": 31, "99acres": 58, "nobroker": 24},
        {"month": "Dec", "housing": 42, "magicbricks": 31, "99acres": 58, "nobroker": 24},
        {"month": "Jan", "housing": 46, "magicbricks": 33, "99acres": 74, "nobroker": 22},
        {"month": "Feb", "housing": 50, "magicbricks": 34, "99acres": 90, "nobroker": 52},
        {"month": "Mar", "housing": 44, "magicbricks": 49, "99acres": 68, "nobroker": 54},
        {"month": "Apr", "housing": 52, "magicbricks": 43, "99acres": 84, "nobroker": 57},
        {"month": "May", "housing": 48, "magicbricks": 46, "99acres": 96, "nobroker": 60},
    ],
}

TRUST_SCORE_TREND_BY_RANGE = {
    "7d": [
        {"date": "Mon", "score": 64},
        {"date": "Tue", "score": 62},
        {"date": "Wed", "score": 65},
        {"date": "Thu", "score": 60},
        {"date": "Fri", "score": 59},
        {"date": "Sat", "score": 58},
        {"date": "Sun", "score": 57},
    ],
    "1m": [
        {"date": "W1", "score": 68},
        {"date": "W2", "score": 65},
        {"date": "W3", "score": 63},
        {"date": "W4", "score": 60},
    ],
    "3m": [
        {"date": "Mar", "score": 70},
        {"date": "Apr", "score": 64},
        {"date": "May", "score": 58},
    ],
    "6m": TRUST_SCORE_TREND,
    "1y": [
        {"date": "Jun", "score": 76},
        {"date": "Jul", "score": 74},
        {"date": "Aug", "score": 73},
        {"date": "Sep", "score": 71},
        {"date": "Oct", "score": 69},
        {"date": "Nov", "score": 67},
        {"date": "Dec", "score": 66},
        {"date": "Jan", "score": 64},
        {"date": "Feb", "score": 62},
        {"date": "Mar", "score": 61},
        {"date": "Apr", "score": 59},
        {"date": "May", "score": 58},
    ],
}

TRUST_META_BY_RANGE = {
    "7d": {
        "score": 61,
        "sentiment_score": 42,
        "response_rate": 22,
        "geo_score": 17,
        "total_mentions": 184,
        "positive": 62,
        "negative": 71,
        "neutral": 51,
        "crisis_alerts": 6,
    },
    "1m": {
        "score": 55,
        "sentiment_score": 38,
        "response_rate": 23,
        "geo_score": 16,
        "total_mentions": 612,
        "positive": 198,
        "negative": 224,
        "neutral": 190,
        "crisis_alerts": 18,
    },
    "3m": {
        "score": 48,
        "sentiment_score": 35,
        "response_rate": 23,
        "geo_score": 16,
        "total_mentions": 1580,
        "positive": 512,
        "negative": 548,
        "neutral": 520,
        "crisis_alerts": 42,
    },
    "6m": {
        "score": 24,
        "sentiment_score": 33,
        "response_rate": 23,
        "geo_score": 16,
        "total_mentions": 15,
        "positive": 5,
        "negative": 8,
        "neutral": 2,
        "crisis_alerts": 3,
    },
    "1y": {
        "score": 52,
        "sentiment_score": 36,
        "response_rate": 24,
        "geo_score": 17,
        "total_mentions": 5820,
        "positive": 1890,
        "negative": 2010,
        "neutral": 1920,
        "crisis_alerts": 156,
    },
}


def get_trust_score_response(range_key: str) -> dict:
    key = normalize_time_range(range_key)
    meta = TRUST_META_BY_RANGE[key]
    trend = TRUST_SCORE_TREND_BY_RANGE[key]
    return {
        "score": meta["score"],
        "sentiment_score": meta["sentiment_score"],
        "response_rate": meta["response_rate"],
        "geo_score": meta["geo_score"],
        "trend": trend,
        "breakdown": {
            "total_mentions": meta["total_mentions"],
            "positive": meta["positive"],
            "negative": meta["negative"],
            "neutral": meta["neutral"],
            "crisis_alerts": meta["crisis_alerts"],
        },
    }


def get_sov_trend_for_range(range_key: str) -> list:
    key = normalize_time_range(range_key)
    return SOV_TREND_BY_RANGE[key]
